#Node-anti-affinity - Except in this node it will schedule in other nodes as we have given operator as NotIN
apiVersion: v1
kind: Pod
metadata:
  name: with-node-anti-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: NotIn
            values:
            - gpu
  containers:
  - name: with-node-anti-affinity
    image: nginx